version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: zemeow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-zemeow}
      POSTGRES_USER: ${POSTGRES_USER:-zemeow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-zemeow123}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Removido o script init.sql pois as migrações são feitas pela aplicação
    networks:
      - zemeow_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-zemeow} -d ${POSTGRES_DB:-zemeow}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Opcional: DbGate para administração do banco
  dbgate:
    image: dbgate/dbgate:latest
    container_name: zemeow_dbgate
    restart: unless-stopped
    environment:
      CONNECTIONS: con1
      LABEL_con1: ZeMeow PostgreSQL
      SERVER_con1: postgres
      USER_con1: ${POSTGRES_USER:-zemeow}
      PASSWORD_con1: ${POSTGRES_PASSWORD:-zemeow123}
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres
    ports:
      - "${DBGATE_PORT:-3000}:3000"
    networks:
      - zemeow_network
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - admin

  # Webhook Tester para testar webhooks do ZeMeow
  webhook-tester:
    image: tarampampam/webhook-tester:latest
    container_name: zemeow_webhook_tester
    restart: unless-stopped
    environment:
      - LISTEN_ADDR=0.0.0.0
      - LISTEN_PORT=8080
      - MAX_REQUESTS_PER_SESSION=1000
      - SESSION_TTL=24h
      - STORAGE_DRIVER=memory
      - CREATE_SESSION=true
    ports:
      - "${WEBHOOK_TESTER_PORT:-8090}:8080"
    networks:
      - zemeow_network
    profiles:
      - webhook-test

volumes:
  postgres_data:
    driver: local

networks:
  zemeow_network:
    driver: bridge