version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: zemeow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-zemeow}
      POSTGRES_USER: ${POSTGRES_USER:-zemeow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-zemeow123}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Removido o script init.sql pois as migrações são feitas pela aplicação
    networks:
      - zemeow_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-zemeow} -d ${POSTGRES_DB:-zemeow}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Opcional: pgAdmin para administração do banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: zemeow_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@zemeow.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - zemeow_network
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - admin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  zemeow_network:
    driver: bridge