version: '3.8'

services:
  # PostgreSQL - Banco de dados principal
  postgres:
    image: postgres:15-alpine
    container_name: zemeow_postgres_dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-zemeow_dev}
      - POSTGRES_USER=${POSTGRES_USER:-zemeow_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-zemeow_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - zemeow_dev_network

  # MinIO - Armazenamento de mídias
  minio:
    image: minio/minio:latest
    container_name: zemeow_minio_dev
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_dev_data:/data
    networks:
      - zemeow_dev_network

  # Redis - Cache e sessões
  redis:
    image: redis:7-alpine
    container_name: zemeow_redis_dev
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - zemeow_dev_network

volumes:
  postgres_dev_data:
  minio_dev_data:
  redis_dev_data:

networks:
  zemeow_dev_network:
